### ISSUE TITLE
Need example site / project to run with this library

### ISSUE THREAD

**Issue by roniardev** [KolbySisk/next-api-route-middleware#2]
Hello @KolbySisk , this is great library to work with next
But, it's hard to understand how it's "works" with existing next js project.
I think is need to add example project to work with this library

like should i use ```middleware.ts``` or add in ```/page/api``` to integrate it in my next js project

**Comment by KolbySisk** [comment]
Thanks for the feedback Roni.

Here is an example project: https://github.com/KolbySisk/pro-api-routes

I'll add an example to this repo soon 👍

**Comment by KolbySisk** [comment]
To be clear, this is not edge middleware that Next makes available via `middleware.ts`. This is code that runs before an api handler is invoked similar to [Express middleware](https://expressjs.com/en/guide/using-middleware.html).

**Comment by roniardev** [comment]
Thanks for your reply, your example project https://github.com/KolbySisk/pro-api-routes
is helped me to understand how to use [next-api-route-middleware](https://github.com/KolbySisk/next-api-route-middleware).

I close this issue
