### ISSUE TITLE
Will this repo and the npm package be maintained ?

### ISSUE THREAD

**Issue by martinIvovIv** [KolbySisk/next-api-route-middleware#4]
I found this repo through the [awesome article ](https://engineering.udacity.com/using-middleware-in-next-js-api-routes-50b7bbb0845) the author made. 
It's easy to copy the code of the package in my repo but I would prefer if it was maintained. I have a project running an older version of next so this package fits me well.

Is it going to be maintained and could other contribute ? 

@KolbySisk

**Comment by KolbySisk** [comment]
Yes, it will be maintained. I use it for all of my projects.

I'll happily review any PRs if anyone else wants to contribute.
